airbnb/binaryalert

rules/public/public.yara

to: @airbnb/binaryalert-maintainers 
**Changes**
1. Added `fidelity` key
2. Tightened `jtesta_ssh_mitm` - 2 conditions now
3. TIghtended `macos_wirelurker` - remove domain condition and address MRT fp's
4. Remove improper uses of `nocase`
5. Add coverage for masscan via `hacktool_masscan`
6. Remove extra spacing that didn't need to exist
Better Yara rule organization will come in a future PR
**Testing**
`yara public.yara ...`

binaryalert - rule cleanup and masscan addition

---

lambda_functions/analyzer/binary_info.py
tests/lambda_functions/analyzer/main_test.py

This PR aims to resolve issue: #24 
**What:**
- Information about each matched rule now a top-level key
- Total number of matches are displayed
**Why:**
- Formatting change should make the output in PagerDuty easier to read.

[OUTPUT] Flatten SNS alert for better PagerDuty formatting

---

README.md
manage.py
terraform/cloudwatch_metric_alarm.tf
tests/boto3_mocks.py

After #28 introduced `moto` to the unit test framework, the batcher invocation during `python3 manage.py deploy` breaks with an error like the following:
```
requests.exceptions.ConnectionError: Connection refused: POST https://lambda.REGION.amazonaws.com/2015-03-31/functions/FUNCTION_NAME
```
Due to https://github.com/spulec/moto/issues/1026, `moto` mocks are not always restored correctly. This means that after the unit tests run, part of `boto3` was still mocked out.
As a simple workaround, I've added a decorator which manually restores the underlying `HTTPAdapter` after running the unit test suite.
- Fixes a link in README
- Fixes Dynamo metric alarm to reference generic `ThrottledRequests` instead of `ReadThrottleEvents` specifically
CI and deployed to an empty test account. Batcher …

Force-remove mocks after tests to fix batcher invocation during deploy

---

.pylintrc
lambda_functions/build.py
manage.py
tests/boto3_mocks.py
tests/lambda_functions/build_test.py

Splits out the Lambda building logic into a separate file and restructures `manage.py` as a class. This has a number of benefits:
- Fixes a TODO where the config file was parsed twice 
- Isolating the build logic makes it easier to test (tests have been added) and easier to add new functions (e.g. #29) 
- Adding future commands (e.g. #23 ) will be easier
Unit tests

Refactor manage.py

---

lambda_functions/analyzer/binary_info.py
tests/lambda_functions/analyzer/main_test.py

**What**
Converted current dynamic keys to static top level keys in the following files:
- `binary_info.py` 
- `main_test.py` 
**Why**
- BinaryAlert: Issue https://github.com/airbnb/binaryalert/issues/24 caused the functionality between StreamAlert and BinaryAlert to cease after the format of the output was changed. 
- StreamAlert is currently unable to handle dynamic, top-level keys because due to the open issue found here: https://github.com/airbnb/streamalert/issues/150
- BinaryAlert has been modified to send static top level keys until this issue is resolved in StreamAlert.
**Tests**
Passed Locally

[StreamAlert] Fix dynamic keys to work with StreamAlert

---

manage.py

`python3 manage.py live_test` has been added, which will:
1. Upload an EICAR test file to the BinaryAlert S3 bucket
2. Search for the YARA match information in Dynamo and print it
3. Remove the test file and resulting Dynamo entry regardless of whether the test was successful
Resolves: #23 
This also alphabetizes all of the CLI commands in the `Manager` class
```
(venv)$ python3 manage.py live_test
Uploading EICAR test file S3:[bucket]:eicar_test_0f5fabe7-e515-4666-97b4-ad17fc34eca4.txt...
EICAR test file uploaded! Connecting to table DynamoDB:[table]...
[1/10] Querying DynamoDB table for the expected YARA match entry...
[2/10] Querying DynamoDB table for the expected YARA match entry...
[3/10] Querying DynamoDB table for the expected YARA match entry...
[4/10] Querying DynamoDB table for …
```

Add live_test option to CLI

---

.coveragerc
.travis.yml
README.md
requirements.txt
requirements_top_level.txt

Add `coverage` instrumentation. Unit tests can now be run with `coverage run manage.py test`
We require 85% coverage for all future PRs for now (that number will increase in the future)
Resolves: #3 

Add coveralls and require 85% test coverage

---

manage.py

This commit was supposed to be in the last PR (#36), I accidentally merged too soon.
If the live_test fails, then by definition the Dynamo entry is not present, so there is no need to try to remove it.
Deploy in test account and `python3 manage.py live_test`
to: @jacknagz or @mime-frame 

live_test remove DynamoDB only on success

---

manage.py
rules/update_rules.py

Size: small
Resolves: #25 
The following subcommands now check for a non-empty prefix and region before executing: `apply`/`deploy`, `analyze_all`, `live_test`
In particular, this prevents a deploy with an empty name prefix:
```
$ python3 manage.py apply
InvalidConfigError: "aws_region" and "name_prefix" must be non-empty strings defined in binaryalert/terraform/terraform.tfvars
```
Resolves: #26
Improves the process for cloning YARA rules in the following ways:
- Only remove the specified subfolders instead of the entire `github.com/` rules directory
- Use shallow clones to reduce cloning time
- Remove the temporary cloning directory if it already exists
- Tried running commands with an empty/non-empty name prefix
- Several different invocations of `update_rules`
to: @jacknagz 
cc: …

Verify config before deploy and improve update_rules

---

README.md
terraform/terraform.tfvars

Clarify that Python3.6 is the precise required version and remove the '.' from the `name_prefix` config example, since periods are not allowed in some resource names

Clarify Python version and name_prefix example

---

lambda_functions/analyzer/main.py
tests/lambda_functions/analyzer/main_test.py

A careful look at the [S3 event notification documentation](http://docs.aws.amazon.com/AmazonS3/latest/dev/notification-content-structure.html) reveals that the included S3 object key is URL-encoded.
This PR changes the analyzer to URL-decode the S3 key from the notification record before trying to download from S3.
Resolves: #4 
Changed the unit tests to url-encode the filenames when invoking the main handler.
Test deploy followed by a manual upload of `space plus+test.txt` was analyzed correctly.
Size: tiny
to: @jacknagz 

URL-decode S3 keys from the event notification

---

README.md
manage.py
terraform/main.tf

Upgrades to Terraform v0.10! This lets us upgrade to the latest AWS provider and supports interactive approval during each `apply` operation.
No work is required for users to upgrade as long as the latest `terraform` binary is in their PATH.
During a deploy, the user is now required to explicitly approve the changes for the main `apply`. However, the second `apply` (which only updates Lambda aliases) happens automatically, because it shouldn't even be necessary. If the Lambda function updates (and the user approves), then its alias will have to update as well. It would also be annoying for the user to have to explicitly approve twice on every deploy.
Resolves: #32 (Terraform v0.10)
Required for: #6 (Cloudwatch dashboard)
Tested with a deploy and `live_test`. A deploy now looks like this: …

Upgrade to Terraform v0.10

---

.gitignore

to: @austinbyers 
Ignore `compiled_yara_rules.bin`, which is generated when locally compiling YARA rules.

gitignore - compiled_yara_rules.bin

---

lambda_functions/downloader/README.md

I believe the correct event type for the notification of a binary being stored successfully on the server is binarystore.file.added
https://github.com/carbonblack/cbapi/tree/master/server_apis#new-binary-file-arrival

CB event type should be binarystore.file.added

---

rules/public/hacktool/macos/hacktool_macos_exploit_cve_2015_5889.yara
rules/public/hacktool/macos/hacktool_macos_juuso_keychaindump.yara
rules/public/hacktool/macos/hacktool_macos_keylogger_b4rsby_swiftlog.yara
rules/public/hacktool/macos/hacktool_macos_keylogger_caseyscarborough.yara
rules/public/hacktool/macos/hacktool_macos_keylogger_dannvix.yara
rules/public/hacktool/macos/hacktool_macos_keylogger_eldeveloper_keystats.yara
rules/public/hacktool/macos/hacktool_macos_keylogger_giacomolaw.yara
rules/public/hacktool/macos/hacktool_macos_keylogger_logkext.yara
rules/public/hacktool/macos/hacktool_macos_keylogger_roxlu_ofxkeylogger.yara
rules/public/hacktool/macos/hacktool_macos_keylogger_skreweverything_swift.yara
rules/public/hacktool/macos/hacktool_macos_manwhoami_icloudcontacts.yara
rules/public/hacktool/macos/hacktool_macos_manwhoami_mmetokendecrypt.yara
rules/public/hacktool/macos/hacktool_macos_manwhoami_osxchromedecrypt.yara
rules/public/hacktool/macos/hacktool_macos_n0fate_chainbreaker.yara
rules/public/hacktool/macos/hacktool_macos_ptoomey3_keychain_dumper.yara
rules/public/hacktool/windows/hacktool_windows_moyix_creddump.yara
rules/public/malware/macos/malware_macos_apt_sofacy_xagent.yara
rules/public/malware/macos/malware_macos_bella.yara
rules/public/malware/macos/malware_macos_marten4n6_evilosx.yara
rules/public/malware/macos/malware_macos_neoneggplant_eggshell.yara
rules/public/malware/multi/malware_multi_pupy_rat.yara
rules/public/malware/multi/malware_multi_vesche_basicrat.yara
rules/public/malware/windows/malware_windows_apt_red_leaves_generic.yara
rules/public/malware/windows/malware_windows_apt_whitebear_binary_loader_1.yara
rules/public/malware/windows/malware_windows_apt_whitebear_binary_loader_2.yara
rules/public/malware/windows/malware_windows_apt_whitebear_binary_loader_3.yara
rules/public/malware/windows/malware_windows_t3ntman_crunchrat.yara
rules/public/malware/windows/malware_windows_xrat_quasarrat.yara

Adds 25 more YARA rules, including hacktools and malware for both OSX and Windows
TravisCI
to: @mime-frame 

Add more public YARA rules

---

README.md
docs/source/conf.py
requirements.txt
requirements_top_level.txt
terraform/cloudwatch_dashboard.tf

This modifies the sphinx doc-building to use the Read-The-Docs theme. Now the `docs/conf.py` is nearly the same as the one in StreamAlert.
This also fixes the S3 metrics in the CloudWatch dashboard to reference the appropriate storage types.

Add rtd-theme and fix S3 metric in dashboard

---

docs/source/adding-yara-rules.rst
docs/source/architecture.rst
docs/source/deploying.rst
docs/source/index.rst
docs/source/uploading-files.rst
terraform/cloudwatch_dashboard.tf

This adds 3 new pages to the documentation:
- **Architecture**: Copied from top-level README
- **Deploying**: `manage.py deploy`, Terraform state, and tearing down infrastructure
- **Uploading Files**: Information about how to upload files to S3, including the CarbonBlack integration
This PR also shortens the dashboard annotation labels so they don't take up as much of the graph.
Contributes to: #2 
Documentation is almost done, we still need:
- To remove redundant READMEs
- Configuration (configuring alert outputs, terraform.tfvars configuration)
- Metrics and Monitoring
- Troubleshooting
to: @mime-frame 

Add documentation for architecture, deploying, and uploading files

---

README.rst

Adds a badge to the README for the slack channel.
This is the last commit before v1.0; I've deployed in a test account and run lots of tests.

Add Slack README badge

---

manage.py

to: @javuto or @ryandeivert 
size: tiny
There is a typo in one of the `InvalidConfigError` messages which flags an invalid `encrypted_carbon_black_url` (which does not exist) instead of the `encrypted_carbon_black_api_token`

Fix error message typo

---

lambda_functions/analyzer/README.rst

to: @chunyong-lin 
size: tiny
#79 added `yextend` and instructions for how to build it. However, there is a typo in the README.
* Fix `autoconf` typo
* Proactively add `bzip2-devel` to the list of `yum` packages in order to compile the latest version of `yextend`
- Compiled `yextend` (both v1.5 and latest master commit) using these install instructions verbatim from a fresh EC2 instance

Fix typo and add bzip2-devel to yextend requirements

---

manage.py

to: @javuto 
size: tiny
resolves #83 
As BinaryAlert releases new versions, it's helpful to know/verify which version someone is running.
* Adds a `--version` flag
`./manage.py --version`

Add --version flag

---

docs/source/getting-started.rst
docs/source/iam-group.rst
docs/source/index.rst

size: medium
resolves: #67 
resolves: #74
* Add instructions to install OpenSSL development libraries before installing BinaryAlert dependencies (to avoid problems with `hash` module).
* Show a least-privilege IAM policy that can be applied to a BinaryAlert admin group.
Documentation compiled and viewed locally.

Add documentation for IAM policy and openssl header installation

---

lambda_functions/analyzer/binary_info.py
tests/lambda_functions/analyzer/main_test.py

size: small
Since BinaryAlert is designed to run in an enterprise environment, it may be scanning sensitive files. Ideally, we could avoid disk entirely and scan everything in memory, but unfortunately this is not yet possible with `yextend`. Instead, we can do our best to shred the file contents before deleting them.
* Use the `shred` utility instead of just truncating files after the analyzer is finished with them.
- `./manage.py deploy` and `./manage.py live_test`

Shred downloaded files when exiting

---

docs/source/analyzing-files.rst
docs/source/index.rst
lambda_functions/analyzer/main.py
lambda_functions/analyzer/yara_analyzer.py
lambda_functions/batcher/main.py
lambda_functions/build.py
lambda_functions/dispatcher/main.py
terraform/lambda.tf
tests/lambda_functions/analyzer/main_test.py
tests/lambda_functions/batcher/main_test.py
tests/lambda_functions/dispatcher/main_test.py

to: @javuto 
size: medium
resolves: #70 
resolves: #72
* All `main.py` files are touched during a deploy to guarantee that every Lambda function is always updated (#70)
* The analyzer now reads the S3 bucket name from the event instead of from an environment variable, which allows it to scan other existing buckets
* The dispatcher and batcher are updated to use the new record format
* Adds documentation which explains how to use BinaryAlert to scan existing buckets
- CI: unit tests, linting, etc
- Deployed to test account, live test, and batch analysis of 10 files

Send bucket name in analyzer event

---

docs/source/deploying.rst
docs/source/getting-started.rst
docs/source/troubleshooting-faq.rst
manage.py
tests/manage_test.py

size: small
resolves: #78 
BinaryAlert deployments with non-empty S3 buckets can't be destroyed by default. This is by design, to protect against accidental data deletion. However, the current process is somewhat cumbersome: you have to manually `terraform apply` a change to `force_destroy = true`.
There was a request for a `manage.py destroy` option, which I am happy to add
* Adds `manage.py destroy` option. If `force_destroy = false` (the default), the user will be prompted whether they want to delete S3 objects as well.
* Updates documentation about the destroy
* Adds a FAQ for the YARA hash issue (see #74 )
Several live deploys and destroys, ensuring that S3 buckets are either deleted or not (depending on input).

Add a destroy command to the CLI

---

rules/public/hacktool/windows/hacktool_windows_cobaltstrike_artifact.yara
rules/public/hacktool/windows/hacktool_windows_cobaltstrike_beacon.yara
rules/public/hacktool/windows/hacktool_windows_cobaltstrike_postexploitation.yara
rules/public/hacktool/windows/hacktool_windows_cobaltstrike_powershell.yara
rules/public/hacktool/windows/hacktool_windows_cobaltstrike_template.yara
rules/public/malware/windows/malware_windows_ccleaner_backdoor.yara

to: @javuto and @mime-frame 
size: medium
* Adds YARA rules which detect different CobaltStrike components
* Adds a YARA rule for the backdoored CCleaner
- CI: Tests that rules compile as expected

YARA rules for cobaltstrike and ccleaner

---

docs/source/getting-started.rst

to: @jacknagz 
size: tiny
#93 was meant to be the release PR, but I forgot to update the version in the Getting Started documentation.
In the future, we should probably find a way to automatically build this number from the configuration

Update version number in getting started

---

terraform/dynamo.tf
terraform/kms.tf
terraform/lambda.tf
terraform/modules/lambda/main.tf
terraform/modules/lambda/variables.tf
terraform/s3.tf
terraform/sqs.tf
terraform/terraform.tfvars
terraform/variables.tf

size: small
AWS [added support for SQS tagging](https://aws.amazon.com/blogs/aws/introducing-cost-allocation-tags-for-amazon-sqs/) a few months ago. Tags make it easier to organize AWS resources, view grouped billing information, etc.
* Add the "Name = BinaryAlert" tag to SQS, as it is already present on all other supported resources
* The value of the "Name" tag is now a Terraform variable (to make it configurable, e.g. for multiple BinaryAlert deployments within the same account)
Unfortunately, because `tags` is a block for Terraform resources, I don't think there's any easy way to make the entire tag map a variable (I tried).
* Terraform validate

Add SQS tag and make tag Name variable

---

docs/source/adding-yara-rules.rst

size: small
Issue #95 brought some questions about fixing or removing YARA rules which aren't supported (e.g. with those with special modules).
* Adds a note to the documentation that we are working on a more expressive rule cloning
* Adds a section to the documentation on how to disable rules files or individual YARA rules
* `sphinx-build -W docs/source docs/build` and viewing built file locally

Add documentation for disabling YARA rules

---

manage.py
terraform/main.tf
tests/manage_test.py

to: @javuto 
size: small
As of [AWS provider v1.10](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1100-february-24-2018), Lambda functions with auto-publish correctly recompute the function versions, obviating the need for our second `terraform apply` during a deploy
* Upgrade AWS provider minimum version to v.11.0 (the latest release)
* Remove second `terraform apply` (a single one works now)
* Remove `terraform validate` - validation automatically happens during `apply`
* Unit tests verify functionality of CLI
* We have other Lambda projects with the new AWS provider which deploy as expected

Upgrade AWS provider and remove now-redundant second apply

---

README.rst
docs/source/index.rst

to: @jacknagz or @mime-frame 
cc: @airbnb/bighead-maintainers 
size: small
The BinaryAlert Twitter account has been deleted, so we remove references to it in documentation and in the README

Remove references to Twitter account which no longer exists

---

lambda_functions/dispatcher/main.py
lambda_functions/downloader/README.rst
lambda_functions/downloader/main.py
terraform/terraform.tfvars
tests/lambda_functions/dispatcher/main_test.py

to: @javuto 
cc: @ryandeivert 
size: small
#112 generalized the dispatcher, but did so by alternating between the different queues and polling from each. The AWS documentation for [SQS Long Polling](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-long-polling.html) recommends instead to have different threads for each queue being polled. This way, the dispatcher is not blocked if one of its queues is empty.
* Use one Process for each queue that the dispatcher is polling
* Fix a small bug in the downloader introduced by #112 and update the downloader README
* Instead of invoking the dispatcher every minute, invoke every 5 minutes and use the maximum long poll timeout (20 seconds)
* Remove custom metrics from the dispatcher. …

Multiprocess dispatcher

---

lambda_functions/build.py
lambda_functions/downloader/main.py
terraform/cloudwatch_dashboard.tf
terraform/cloudwatch_metric_alarm.tf
terraform/sqs.tf
tests/lambda_functions/build_test.py
tests/lambda_functions/downloader/main_test.py

to: @chunyong-lin 
size: small
#112 , #113 , and #114 were some relatively big changes to BinaryAlert, and some problems surfaced when stress-testing in different environments, which we address here.
* Use `subprocess` instead of `pip.main`, which is no longer supported in `pip` v10.0.0
* Change Downloader metadata to accommodate a wider range of possibilities introduced by the new `cbapi`
* Remove units from CloudWatch graph titles (CloudWatch now shows them in the graph itself)
* Fix the DLQ metric alarm - it should look at number of messages, not messages received
* SQS retention has been lowered from the default (4 days) to 12 hours, mostly so that the graph of message age is easier to see. In practice, messages should never stick around that long
* …

Small fixes after stress test

---

lambda_functions/build.py
lambda_functions/downloader/main.py
manage.py
terraform/dynamo.tf
terraform/kms.tf
terraform/lambda_iam.tf
terraform/s3.tf
terraform/sqs.tf
terraform/terraform.tfvars
terraform/variables.tf
tests/lambda_functions/build_test.py
tests/lambda_functions/downloader/main_test.py
tests/manage_test.py

size: medium
BinaryAlert may be processing and storing sensitive information (files scanned, YARA matches, etc). To better protect that data, we can use server-side encryption (SSE) to encrypt data at rest in all supported services (Dynamo, S3, and SQS)
* Pins the `python-dateutil` library when building the downloader function to avoid a `pip` warning
* `CbEnterpriseResponseAPI` has been deprecated by CarbonBlack in favor of `CbResponseAPI`
* Create 2 new KMS keys for server-side encryption of S3 and SQS, respectively. (Dynamo uses its own AWS-managed key)
* Add AWS account ID to the BinaryAlert config (it's required for creating a policy on the new KMS key)
**WARNING:** Enabling server-side encryption for the Dynamo table forces a new …

Enable server-side encryption for Dynamo, S3, and SQS

---

terraform/s3.tf

size: small
#121 enabled server-side encryption with KMS for both BinaryAlert S3 buckets. However, access logs could no longer be delivered after this change.
I'm sure there's a permission error, but I couldn't find it - even granting `kms:*` to `Service: s3.amazonaws.com` for the KMS key didn't work.
Use the default S3 encryption for the access logs bucket instead of KMS. KMS is still used to encrypt the primary bucket (for uploads)
* Access logs delivered successfully after this change

Use SSE-S3 instead of SSE-KMS for access logs

---

rules/clone_rules.py
tests/rules/clone_rules_test.py

clone_rules.py allows for git ssh urls, but fails when trying to create the target_repo_root variable on ssh urls because it only splits on `\\`
to: @airbnb/binaryalert-maintainers
size: small
resolves #15 
See issue for stacktrace
* added split logic for ssh urls
I ran it locally with both https and ssh urls and confirmed they both work

bug with ssh git repo cloning

---

requirements.txt

to: @airbnb/binaryalert-maintainers
cc:
size: small
resolves #127
See #127
* Bump PyYAML to 3.13
Just started trying out binaryalert, `unit_test` still works:
```
(tmp-2ead4cdaa0183929) % ./manage.py unit_test
..................................................................................
----------------------------------------------------------------------
Ran 82 tests in 4.083s
OK
```

Bump PyYAML

---

cli/config.py
lambda_functions/analyzer/analyzer_aws_lib.py
lambda_functions/analyzer/binary_info.py
lambda_functions/analyzer/main.py
manage.py
terraform/cloudwatch_dashboard.tf
terraform/cloudwatch_metric_alarm.tf
terraform/kms.tf
terraform/lambda.tf
terraform/lambda_iam.tf
terraform/sns.tf
terraform/sqs.tf
terraform/terraform.tfvars
terraform/variables.tf
tests/cli/_common.py
tests/cli/config_test.py
tests/lambda_functions/analyzer/main_test.py

to: @chunyong-lin 
size: medium
A few additional configuration options and improved support for direct invocation and scanning external resources.
* Use `true/false` for all "boolean" Terraform values (instead of 0/1)
* Rename `safe_alert` to "negative" or "no-match" alert and consolidate some of the SNS logic (FYI @goochi1 )
* Add support for direct invocation of the BinaryAlert analyzer with an extremely simple event:
```json
{
"BucketName": "bucket-name",
"ObjectKeys": ["key1", "key2"]
}
```
* An existing SNS topic can be used for metric alarms instead of always creating one
* Queue retention periods are now configurable and the associated metric alarms will automatically adjust - alarms will trigger if the oldest message in the queue reaches 75% of …

More configuration options and support direct invocation

---

terraform/s3.tf

to: @Ryxias 
I hadn't realized the logging bucket was optional, and applying a policy to a non-existent optional resource will fail.
* Making bucket policy optional for the logging bucket (will only get applied if the resource also exists).

fixing bug with applying policy to optional resource

---

tests/cli/_common.py
tests/lambda_functions/analyzer/file_hash_test.py
tests/lambda_functions/analyzer/yara_analyzer_test.py
tests/rules/clone_rules_test.py
tests/rules/compile_rules_test.py

to: @airbnb/binaryalert-maintainers
size: small
The unit tests make a few calls to deprecated pyfakefs functions which are throwing warnings. When those functions are eventually removed this could break. Until then it clutters the test output.
An example of the output can be seen in [Travis][ci].
* Update a few deprecated pyfakefs functions to the new versions
```
./manage.py unit_test
.............................................................................
----------------------------------------------------------------------
Ran 77 tests in 5.601s
OK
```
[ci]: https://travis-ci.org/airbnb/binaryalert/jobs/498882125

Fix pyfakefs deprecation warnings

---

lambda_functions/downloader/main.py
terraform/modules/lambda/variables.tf

to: @airbnb/binaryalert-maintainers 
cc: 
size: small
A recent change in our Binary exfill service is causing a race condition where the triggering event is firing before the resource is actually available through the API. This causes the URL to 404. Currently, BinaryAlert WILL NOT RETRY downloading, thus dropping the analysis of that file.
The issue is that the binary will eventually show up, typically within a few minutes. Changing the handling to 404 will cause the binary to 
* ObjectNotFoundErrors (HTTP 404) will now retry. This is accompanied by logging that explicitly states that it will retry.
* Internal server errors encountered will now also retry. Improved verbiage that explicitly states that it will retry.
* Raises the error threshold on the downloader to 250. We already have …

Improves error handling to correctly retry downloading md5s

---

cli/config.py
cli/manager.py
lambda_functions/downloader/main.py
terraform/lambda.tf
terraform/terraform.tfvars
tests/lambda_functions/downloader/main_test.py

to: @Ryxias 
I discovered that the [in-memory copy of the binary](https://github.com/airbnb/binaryalert/pull/147) inflates memory usage above the default of 128 mb for the downloader.
* Updating default memory size for downloader to 256mb.
* Increasing retries for the redrive policy since retries should be expected.
* Terraform format of the file.
* Adding ability to specify timeout for cbapi python client.

adding configurable cbapi timeout and updating some tfvars

---

requirements.txt
terraform/cloudwatch_dashboard.tf
terraform/cloudwatch_metric_alarm.tf
terraform/dynamo.tf
terraform/kms.tf
terraform/lambda.tf
terraform/lambda_iam.tf
terraform/main.tf
terraform/modules/lambda/main.tf
terraform/modules/lambda/outputs.tf
terraform/modules/lambda/variables.tf
terraform/modules/lambda/versions.tf
terraform/s3.tf
terraform/sns.tf
terraform/sqs.tf
terraform/variables.tf
terraform/versions.tf

to: @airbnb/binaryalert-maintainers
size: medium
* Upgrades Terraform syntax on all modules to 0.12
* Upgrades `pyhcl` to 0.4.0 to be Terraform 0.12 compatible
I sync'd internally and tested a `terraform plan`, which works.... **with some tweaking**.

Upgrades terraform modules to Terraform 0.12.9
